### ISSUE TITLE
When installing 0.10.53, I get the following error from yarn

### ISSUE THREAD

**Issue by wpwood** [medikoo/es5-ext#103]
When installing 0.10.53 (which is a subdependency of one of my dependencies), I get the following error from yarn:
```
error https://registry.yarnpkg.com/es5-ext/-/es5-ext-0.10.53.tgz: Integrity check failed for "es5-ext" (computed integrity doesn't match our records, got "sha512-Xs2Stw6NiNHWypzRTY1MtaG/uJlwCk8kH81920ma8mvN8Xq1gsfhZvpkImLQArw8AHnv8MT2I45J3c0R8slE+Q== sha1-k8WjrP2+8nUiCtcmRK0C7hg2jeE=")
```

Looks like it need to be republished, maybe?

Note that 0.10.52 seems to work fine, so I added a:
```
  "resolutions": {
    "es5-ext": "0.10.52"
  },
```

to my package.json as a workaround

**Comment by medikoo** [comment]
@wpwood Thanks for report. Still that looks a problem on Yarn side.

This package is just published to npm registry, and you cannot re-publish already published versions to npm.
I believe that Yarn copied it to its own regsitry, and over there some issues were approached.

**Comment by wpwood** [comment]
Gotcha. Thanks for the help, and I'll close this. Still trying to figure out how to report it on the yarn side, though.
