### ISSUE TITLE
Remove malware

### ISSUE THREAD

**Issue by vadimbublikov** [medikoo/es5-ext#111]
Remove malware given by this commit
https://github.com/medikoo/es5-ext/commit/28de285ed433b45113f01e4ce7c74e9a356b2af2

**Comment by medikoo** [comment]
@vadimbublikov this change is intended. I'd definitely remove it once the aggression stops, and Ukrainians can live in peace in their own country

**Comment by SkReD** [comment]
Please, consider to check the facts comprehensively before inserting such offensive political information in to wide used public code

**Comment by dmitry-ra** [comment]
Adware report was sent to github, npm, tidelift.

**Comment by medikoo** [comment]
For any further discussion please refer to https://github.com/medikoo/es5-ext/issues/116
