### ISSUE TITLE
WTF wrong with you?

### ISSUE THREAD

**Issue by eolme** [medikoo/es5-ext#113]
The NPM package is not a place for politics.

![image](https://user-images.githubusercontent.com/11076888/158024703-34a4068d-2a69-43f6-bf94-e82aff40ee8d.png)

**Comment by svcru** [comment]
Doing this in your product is like urinating at the well you drink from.

**Comment by wwwmigel** [comment]
Programming and politics are incompatible things. I think this is the end of a programmer's career of this author.

**Comment by Piterden** [comment]
Да что вы знаете вообще? Только смотрите видосы и телеграм каналы листаете. Уберите эту чушь из постинсталла!!!

**Comment by regulyarniy** [comment]
make project free from politics

**Comment by greyufo** [comment]
It is unclear why only now stood up in the rack? Why didn’t he write “stop the USA!” about Donbass and the dead children? Why is there nothing in the destroyed Libya, Iraq, Yugoslavia, Syria ?!

**Comment by wolframdeus** [comment]
Remove politics from development. Dont you understand how it is disrespectful for developers from Russia and Belarus? Do you think that IT sector of these countries does not understand what is happening?

We are tired of this shit. We are tired of this shit. We are tired of this shit.

**Comment by svcru** [comment]
Github said that github will always be free of politics. If you do not agree with the position of the site, then this site is not for you, you have nothing to do here.

**Comment by medikoo** [comment]
We've discussed that at https://github.com/medikoo/es5-ext/commit/28de285ed433b45113f01e4ce7c74e9a356b2af2#commitcomment-68471721 Please see my comments over there.

**Comment by medikoo** [comment]
For any further discussion please refer to https://github.com/medikoo/es5-ext/issues/116
