### ISSUE TITLE
WTF wrong this you?

### ISSUE THREAD

**Issue by eolme** [medikoo/es5-ext#114]
The NPM package is not a place for politics.

Closed for no reason.
See: #113

**Comment by icw82** [comment]
@medikoo 

This is not a call for peace, but a call for a revolution, which should not be on github and NPM at all. This is a very stupid act dictated by emotions.

Yes, war is terrible, but none of us know what is really going on there. If you think you know what's going on, you're wrong. There is no need for me, who lives in Russia, to say that I am some kind of stupid that I cannot figure out which sources of information I should use. Don't think we're in an information bubble here. I read news from various sources (including Ukrainian ones) and it is difficult to accept any point of view, because the truth is covered in the fog of war. What about you? Have you met a reasoned alternative point of view?

**Comment by dmitry-ra** [comment]
Adware report was sent to github, npm, tidelift.

**Comment by 2618094** [comment]
@medikoo your are nazi.

**Comment by icw82** [comment]
@2618094 It does not follow from his message that he is a Nazi. However, his act is infantile and unworthy of a professional.

**Comment by medikoo** [comment]
As I mentioned in https://github.com/medikoo/es5-ext/commit/28de285ed433b45113f01e4ce7c74e9a356b2af2 whole point of this manifest, is to help you get to reliable sources of information of what's going on, as you won't get it from official media sources in Russia.

If you know how to get reliable information, simply ignore it, and let others take advantage of it.

Note that I'm affected by the situation directly, and it's why I've decided to put this manifest in.

_Reiterating what I've mentioned before_:

So far, my country (Poland) has welcomed 1.5 million people from war-stricken Ukraine. They are ordinary, regular people, like you and me. Now frightened and without a place to live.

My friends regularly take a car, fill it with basic needs, go to the border, leave the products, and take Ukrainians who fleed their homes, offering them a free ride to one of the major cities. Some others take shifts to help manage situations in large public shelters. I personally let two Ukrainian women stay in one of my flats.

Your army is bombing civilian buildings, hospitals, killing women and children. AFAIK, they see it the only way to crush the spirit of Ukrainians. The result is that many Ukrainians who were skeptical so far about government in Ukraine and where so called pro russions, became now anti-russians.

If you can check this thread: https://twitter.com/kamilkazani/status/1502748765169532928

<img width="495" alt="Screenshot 2022-03-13 at 23 40 46" src="https://user-images.githubusercontent.com/122434/158082339-45ec6e3e-9857-46ce-af16-5da5c570091b.png">
<img width="488" alt="Screenshot 2022-03-13 at 23 42 16" src="https://user-images.githubusercontent.com/122434/158082340-bfd25f1f-e014-4ee6-ad43-a25097c560db.png">

When I'll have time I'll post in this thread some news on war in Ukrainie which you have no chance to see in official Russian media.

Note, that I won't answer any not constructive comments.

**Comment by eolme** [comment]
You're just dumb if you think it helps anything. You only incite hatred not only of yourself, but also of Ukrainians. What the fuck? Do you hate ordinary Russians so much? We are not military or politicians. Go to hell.

**Comment by eolme** [comment]
This is hate speech, nothing more and nothing less. I hope you come to your senses.

**Comment by icw82** [comment]
@medikoo 

“If you know how to get reliable information, simply ignore it, and let others take advantage of it” — I don't know any of my colleagues who watch TV or any other kind of obviously propaganda media. The popularity among programmers, designers, artists (and how many intellectual professions in general) of such sources is very small. Therefore, your manifesto has no positive effect, but only increases the level of stress.

I do not like to see political statements in an apolitical professional or scientific environment. I have enough of those sources to which I am subscribed.

If you think that people with at least some brains watch propaganda TV programs or news on Russian television, you are radically mistaken. Almost all of them have been using alternative sources of information for a long time. Unfortunately for me, among them there are also propagandist media, but of the opposite direction, focusing on one point of view. I see this by comparing completely different sources of information.

From what you have written, I do not see anything new that I have not read or seen before. Something true, something speculation, something fake, or just emotions. Even people I know who have relatives in Ukraine receive completely different information. In the fog of war, it is impossible for the average person to understand what is really happening.

**Comment by icw82** [comment]
@eolme

Пожалуйста, воздержитесь от оскорблений — они не помогают, а лишь усугубляют.

**Comment by medikoo** [comment]
For any further discussion please refer to https://github.com/medikoo/es5-ext/issues/116
