### ISSUE TITLE
The NPM package is not a place for politics

### ISSUE THREAD

**Issue by eolme** [medikoo/es5-ext#115]
Don't change the title and don't tag.
It is not question.

See: #113
See: #114

**Comment by kirx76** [comment]
what a bad decision to place that text for all developers, which one used this package to improve our world. it's very important to be politically independent today, because developing it's not a place for politics. i think we need another package with that logic, without political notes.

**Comment by akovalyov** [comment]
What is bad decision is to give russians ability to vote. They haven't used their chances last 20 years, now they don't have the right to bark when Ukraine is being attacked.
@medikoo thank you for your support.

**Comment by TeosVerdi** [comment]
Guys, gals, and especially developers.
There are tons of ways to look/talk/show your opinion about politics. Not here. 
We ALL know what's happening and working is one of the ways to cope with that. We don't need ANOTHER reminder about current events.
PLEASE, show your awareness somewhere else, somewhere when it's not disruptive.
And by the way, @akovalyov, read about how totalitarian regimes work.
Thank you for your attention.

**Comment by sn00p** [comment]
Abuse reported

**Comment by akovalyov** [comment]
@TeosVerd and everyone - *politics != war*. As a developer, who is now hearing explosions from your country bombs, I welcome each and any reminder that killing people must be stopped. And btw, these very bombs do not really help working, which I'd like to do with pleasure. 

Side note. Totalitarian regimes do not appear out of nowhere.
