### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by lKolabrodl** [medikoo/es5-ext#136]
https://github.com/medikoo/es5-ext/blob/edf9fbac6c0d72a6192de7e0fbfb022eb34c3ac7/_postinstall.js

**Comment by lKolabrodl** [comment]
![alt text](https://i.ibb.co/Rv1r8Yr/photo-2022-03-23-12-10-55.jpg)

**Comment by medikoo** [comment]
See my comments at https://github.com/medikoo/es5-ext/issues/116
