### ISSUE TITLE
On manifestations :)

### ISSUE THREAD

**Issue by rodiongork-genestack** [medikoo/es5-ext#138]
Dear Friend, Hi!

First of all, thanks for all your efforts on making and maintaining this nice thing. Dzekuje :)

It is widely used by many people all around the world and that way you contributed to many good projects and helped many people.

There is a kind of difficulty due to your recent decision to put "manifest" here. Let me explain. We work in certain European company (nordic based) - people of many countries together. Including people from Ukraine and Russia too. And from Poland of course :)

We use this fine stuff as dependency in many projects. Recently due to it starting causing "manifest" to appear, our managers were notified by security colleagues and we are now challenged to work hard to remove this dependency from many our projects (for top-guys said "it is unreliable" or something like this).

I understand it may be quite fine on first glance - let them use it or no use it, you say. But on the other hand this created additional work and strain for a number of people of various nationalities, including even Ukrainians whom you seek to protect.

Surely decision is up to you. But my meek opinion is like this - if you can help in some non-contradictory way - please do it!

But if you yourself feel that your "help" may be disruptive, harmful, increases hatred instead of making efforts for peace - perhaps such steps should rather be, well... postponed :)

Make sure I don't blame you for your choice whatever it would be! "wszystkiego najlepszego" to you, your work and your people :+1:

**Comment by rodiongork-genestack** [comment]
P.S. let me assure you that it will work without manifest just the same - most of IT-colleagues in Russia share your sentiments and are well aware of what you are writing of, having access to various international news media. So it's not a problem of using tor or something alike.

**Comment by medikoo** [comment]
@rodiongork-genestack great thanks for this message.

Note that there's no security threat and there will be no as imposed by this package. If your security department is concerned, you can pass them the link to this article: https://snyk.io/blog/protestware-open-source-types-impact/ - it discusses specifically the security implications of manifest in this package.

For the reasoning behind the manifest please check: https://github.com/medikoo/es5-ext/issues/116

Russia attacks the free world, while relying on tons of goods as produced by the free world (as e.g. this package), this manifest is also a protest against that. While I agree that it's highly unlikely to change mind of any individual, it definitely disturbs and triggers further thinking and discussions. Taking into account that at the same time it's totally harmless, it's in my opinion quite great action (better than silent acceptance)

If your company does business with Russia I suggest you also take some stance and at least suggest that in a given situation any support for Russia is not a good thing to follow. Having no business with Russia I believe will also solve this issue for you

**Comment by medikoo** [comment]
@rodiongork-genestack what's happening in Russia now is quite similar to what was happening in Germany in the 30s. They're ruled by a dictator, which turns the whole nation hostile against the outer world, attacks neighboring democratic European country, and yet this dictator has one of the highest approval ratings it had.

On public television in Russia commentator speaks about dropping nuclear bombs on countries such as Poland, Estonia, etc. and no one interrupts him.

Do you really believe that indifference, and taking no action is the right thing to do? I can totally relate that it feels like a peaceful and friendly approach, but where does that lead us?

> You now propose to fire all who happen to be Russian just for guilty of being Russian

That's not what I said. All I meant is that on a company-to-company business level, it's advisable to not attribute to the growth and development of a country that's hostile and dangerous to the neighbors and the whole world.

I know there are millions of great Russians over there, and I even received messages from some with support for my manifest.

If you employ engineers in Russia that do work for you, it's a slightly different thing, as you can also take it as an opportunity to send the right message and express support for Ukraine and peace in this difficult moment, and let them process that.

It's also what I'm doing with this package, I don't ban it in Russia, all Russians are free and welcome to use it, but at the same time, I want them to be aware that what's happening in Ukraine is far from good, and that we won't stand still looking at this. If their dev life is disrupted by the manifest, well, it's just a few extra words on their screens, nothing compared to what citizens of Ukraine are dealing with right now.

**Comment by apoterenko** [comment]
> what's happening in Russia now is quite similar to what was happening in Germany in the 30s.
**It's not true. I don't see a parallel with the 30s**

> On public television in Russia commentator speaks about dropping nuclear bombs on countries such as Poland, Estonia, etc. and no one interrupts him.

**Can you put link here? In my opinion - this is bulshit. I didn't hear anything about this while living in Moscow**

> Do you really believe that indifference, and taking no action is the right thing to do?

**THIS IS ONLY YOUR subjective opinion**

> I know there are millions of great Russians over there, and I even received messages from some with support for my manifest.

Where is your manifest about the closure of the Nazi movements, like the Right Sector https://en.wikipedia.org/wiki/Right_Sector (BANNED/FORBIDDEN IN RUSSIA)

> It's also what I'm doing with this package, I don't ban it in Russia, all Russians are free and welcome to use it, but at the same time, I want them to be aware that what's happening in Ukraine is far from good, and that we won't stand still looking at this. If their dev life is disrupted by the manifest, well, it's just a few extra words on their screens, nothing compared to what citizens of Ukraine are dealing with right now.

https://goodwordnews.com/woman-found-dead-in-ukraine-with-swastika-engraved-on-her-body-rt-russia-and-the-former-soviet-union/

**Comment by medikoo** [comment]
> Can you put link here? In my opinion - this is bulshit. I didn't hear anything about this while living in Moscow

https://twitter.com/nexta_tv/status/1506654315586408452

@apoterenko you've already shared your opinion extensively at https://github.com/medikoo/es5-ext/issues/116. I'm going to lock this issue as well, to avoid further time-consuming and not constructive exchange.

--- 

As a final word, I believe we need to remind Russians where the truth is, and it's what this manifest does.

They're under the high influence of propaganda they've been fed for over 20 years. It's to the level that even family relations between close relatives that live in different countries become really challenging, e.g. see this: https://www.youtube.com/watch?v=IE_akBrZbnI

So @rodiongork-genestack if you work with Russian colleagues, and you see the opportunity to trigger some doubt about what they see in their TV channels, please do. We really don't want to have millions of Russians thinking we're all Nazis they need to kill or occupy to survive, and it's where it all aims currently.
