### ISSUE TITLE
How do you explain this? 

### ISSUE THREAD

**Issue by apoterenko** [medikoo/es5-ext#139]
Literature of ukeronazism. Who printed these books?

https://www.youtube.com/watch?app=desktop&v=t-_uKVO7doM

**Comment by medikoo** [comment]
@apoterenko please come to Poland, and check by yourself if those 2+ million of Ukrainians fleeing their homes, are nazis.

I see them and speak to them nearly every day. They're not, and their Jewish president which lost family in the holocaust is neither.
