### ISSUE TITLE
Polland is Nazzi? WTF you are noob!

### ISSUE THREAD

**Issue by freexmonster** [medikoo/es5-ext#144]
Dear author, you support the nationalist regime of Ukraine and you are a criminal and a Nazi. Imagine that a Nazi came into your apartment, raped your wife and children. You went out to the balcony and shouted "I have a rapist! Help!"
Russia in this situation is a policeman. And she must catch all the Nazis and condemn them. But an onlooker comes up to the policeman and says, "Don't go there and there won't be any problems."
"Let the Nazis continue to rape and kill .... in that house, not in your own"

What should Russia do in this case?

Once the Germans shouted after the Jews - "Get out of here ..."
We see exactly the same thing there, only now you are doing it with the Russians.
You are a disgrace to mankind. Your grandfather would be rolling over in his grave. Damn you. You are the same Nazi, live with it.

**Comment by freexmonster** [comment]
WTF!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    https://www.youtube.com/watch?v=lRtLFT2sbBg

**Comment by medikoo** [comment]
Please see #116
