### ISSUE TITLE
This is not malware, but...

### ISSUE THREAD

**Issue by xsrvmy** [medikoo/es5-ext#185]
In response to #116
Some are calling this malware, but unless I'm missing something else in the package, printing in the console for the developer is not malware. The word malware literally means "malicious software", and there is no malicious software. (Please don't debate this, not the place for it). The dogma literally came from node-ipc. I also totally understand that you are affected by this. We might all be affected (oil prices rose by like 80% in Canada here).

That being said, in 2018/9, there was an incident where standardjs and logrocket posted ads in the terminal similar to this postinstall, and npm changed their repo tos to not allow this behaviour. The current behaviour is somewhat similar. Additionally I heard that postinstalls causes different behaviour in some package managers so it's not supposed to be used unless absolutely necessary.

Please consider removing the postinstall script given the reasons I have given above.

**Comment by medikoo** [comment]
@xsrvmy closing, as all explanations were provided at #116 

It'll definitely be removed, once the Russian army leaves Ukraine, and will accept it as a sovereign independent country.

Note that manifest is shown only to developers being in Russia
