### ISSUE TITLE
Political bug

### ISSUE THREAD

**Issue by glebpavlov** [medikoo/es5-ext#193]
https://github.com/medikoo/es5-ext/blob/78e041fe780ab39e73b7e580407e3ce1e52f4e38/_postinstall.js#L31

Кто-то внес свою политоту в ИТ. Как недосмотрели?
Пример ужасной халатности!

**Comment by artemukolov** [comment]
@glebpavlov это обновление внес главный контрибьютор - @medikoo . Я общался с ним. Он считает что в праве использовать репозиторий для политических высказываний.

**Comment by glebpavlov** [comment]
Как глупо.

Кстати, продам гараж в СПб, пишите в ЛС

**Comment by medikoo** [comment]
Please use just English language and see #116 for reasoning of included manifest
