### ISSUE TITLE
Error: ELOOP: too many symbolic links encountered

### ISSUE THREAD

**Issue by Alpsli** [medikoo/es5-ext#194]
es5-ext -> es6-iterator -> d -> es5-ext -> ...

![image](https://user-images.githubusercontent.com/52439609/190222877-0053e2de-9c3e-4603-9207-b702b3079eab.png)

**Comment by medikoo** [comment]
@Alpsli circular references are totally valid in npm ecosystem. This error signals some issue with your setup

**Comment by medikoo** [comment]
@Alpsli closing this due to lack of input
