### ISSUE TITLE
fu'ed postinstall message

### ISSUE THREAD

**Issue by KarelWintersky** [medikoo/es5-ext#196]
![image](https://user-images.githubusercontent.com/2164874/220331907-e1400231-89cb-48ac-9efe-2948b524e758.png)

WTF?

**Comment by KarelWintersky** [comment]
Where were you when Ukraine shelled Donbass for 8 years?

Does the name "Avenue of Angels" mean anything to you?

Or "it's different"?

**Comment by medikoo** [comment]
@KarelWintersky see https://github.com/medikoo/es5-ext/issues/116

Concerning Donbas, I'm taking information from resources such as https://en.wikipedia.org/wiki/War_in_Donbas_(2014%E2%80%932022). None of it justifies a full-scale invasion of Ukraine
