### ISSUE TITLE
Clean repo from Malware scripts

### ISSUE THREAD

**Issue by sinxwal** [medikoo/es5-ext#197]
I cannot use this package in my project anymore, because __postinstall.js_ file is detected as malware and is deleted by ZoneAlarm Firewall.

Forcing people to fork good and maintainable repo is crazy, wtf is going on... Please, don't defame open source software, we must take care of it.

**Comment by medikoo** [comment]
@sinxwal there's no [malware](https://en.wikipedia.org/wiki/Malware) in this package, You should report that to ZoneAlarm Firewall. Please see #186 for more information
