### ISSUE TITLE
Move "call for peace" to `README.md` to avoid unintended consequences

### ISSUE THREAD

**Issue by rjwut-chg** [medikoo/es5-ext#199]
While I have zero issue with the intent of the message in question, using postinstall scripts is problematic. For security reasons, people shy away from packages that have postinstall scripts or disable such scripts, but the bigger issue is unintended consequences like #181, resulting in the package installation erroring out and failing builds. This is not an acceptable cost for functionality that has nothing to do with the package's purpose. Moving the "call for peace" message to the top of `README.md` would still retain high visibility, without the risks of using a postinstall script.

**Comment by medikoo** [comment]
@rjwut-chg let's keep discussion under #181, I'm reading all comments there (no need to create another issues)
