### ISSUE TITLE
Why you don't call for peace in Gaza?

### ISSUE THREAD

**Issue by keepitsimple** [medikoo/es5-ext#202]
You call for peace in you project https://github.com/medikoo/es5-ext/blob/main/_postinstall.js#L31-L72 

Israel killed in Gaza more civilians in a few weeks than Russia in 2 years on Ukraine (this is public info in western mass media)

Why you don't call for peace in Gaza? Why are the Palestinians worse? Are they not worthy of protection? If you stand for peace and order, then be consistent in your actions. 

**Otherwise it looks like catching a hype.**

**Comment by medikoo** [comment]
@keepitsimple, As I explained in the original issue, the war in Ukraine affects me directly. The war in Gaza doesn't.

I'm pretty sure any Palestinian (or Israeli, targeting Hamas) developer might be keen to post a similar manifest in the package they author and let us respect that.

All the best. I'm closing and locking to avoid further discussion, which obviously wouldn't be productive.
