### ISSUE TITLE
Failed to exec postinstall script on Linux

### ISSUE THREAD

**Issue by gianggss9292** [medikoo/es5-ext#204]
![2024-02-27_174036](https://github.com/medikoo/es5-ext/assets/132964848/3eab41d1-80b5-4b12-8e8d-c91471ed67da)

**Comment by gianggss9292** [comment]
Thank you for your reply,
I got the above error when doing `npm install gulp -g` after installing es5-ext@0.10.63.
I did the same process but with es5-ext@0.10.62 without any error.
![rp1](https://github.com/medikoo/es5-ext/assets/132964848/eac3f04d-d431-4382-b7c0-5b8fb9fbb254)

**Comment by medikoo** [comment]
@gianggss9292 thanks I believe fix for https://github.com/medikoo/es5-ext/issues/181 exposed this issue.

I'll probably revert that, still it'll be great to know if there's a way to have both issues addressed

**Comment by medikoo** [comment]
Reverted problematic patch, and published with v0.10.64

**Comment by gianggss9292** [comment]
Thank you for your support, I checked again and this bug has been resolved.
