### ISSUE TITLE
tanh returns NaN for values absolutely higher than 709.8

### ISSUE THREAD

**Issue by edouardklein** [medikoo/es5-ext#27]
I ran the following code:
`Math.tanh = require('es5-ext/math/tanh');

for(var i=0.;i>-800;i-=0.1){
  var o = Math.tanh(i);
  if(isNaN(o)){
    console.log(i+' tanh returns NaN');
  }
}

console.log('No NaNs')
`

Expected output was 'No NaNs'. Actual output was:
-709.8000000000928 tanh returns NaN...

**Comment by edouardklein** [comment]
The same bug (not checking for exp returning Infinity) also affects e.g. cosh and sinh. I hope I'll be able to submit a more complete pull request revisiting all hyperbolic functions. I'll try this week-end.

**Comment by medikoo** [comment]
Thanks for PR, it's merged. As a side note, if you want to implemtent `tanh` on Math, it's better if you do:
```javascript
equire('es5-ext/math/tanh/implement');
```
Also, it's not recommended to do it, in any generic packages.

**Comment by medikoo** [comment]
I've also added tests for extreme values to _sinh_ and _cosh_, and doesn't look they share same issue. If however you still think it's the case, please post failing test. Thanks!
