### ISSUE TITLE
Consider remove of `global`

### ISSUE THREAD

**Issue by medikoo** [medikoo/es5-ext#40]
It's controversial as breaks CSP policy, and there are other (without reaching for `global`) clever ways to share something globally so ideally there should be no reason for this module.

**Comment by unarist** [comment]
We'are experiencing this problem (through `es6-symbol`). Are there any updates for this?

Also if you don't have a time for this, how about adding other ways to obtain `global` like [Webpack does](https://github.com/webpack/webpack/blob/master/buildin/global.js)?

**Comment by medikoo** [comment]
@unarist I've addressed it with d38644935d6243c25095f3ee7da77698d116c364

It's published as v0.10.24

**Comment by unarist** [comment]
I've confirmed v0.10.24 fixes the issue. Thanks a lot!

**Comment by medikoo** [comment]
Closing this, as CSP policy issue has been solved and call for removal of `global` util seems not valid. There are valid use cases (as e.g. in es6-symbol's [implement.js](https://github.com/medikoo/es6-symbol/blob/master/implement.js)) which can't be worked around
