### ISSUE TITLE
Resolve cross dependency

### ISSUE THREAD

**Issue by martinheidegger** [medikoo/es5-ext#51]
`es5-ext` is requiring a dependency on `es6-iterator` and `es6-iterator` is requiring a dependency on `es5-ext`. This cross dependency is *not cool* according to npm that dies in a `Maximum call stack size exceeded` message when it's trying to shrinkwrap `es5-ext` (and probably even other cases).

It would be awesome if `es5-ext` or `es6-iterator` could be changed to have only a one-way dependency.

**Comment by martinheidegger** [comment]
Related: https://github.com/npm/npm/issues/13730

**Comment by medikoo** [comment]
@martinheidegger it's intended and this works perfectly with normal install. It's really a bug of npm shrinkrwap, so let's solve this issue at https://github.com/npm/npm/issues/13730

**Comment by martinheidegger** [comment]
@medikoo Thank you for answering. Out of curiosity. What is the intention behind it? Even in consultation with dev-friends I couldn't make out why this would make sense. I would be very grateful for enlightenment.

**Comment by medikoo** [comment]
@martinheidegger sure:

- es5-ext is extensions for ES5, but with respect to the ES6 standard, that's e.g. the reason it provides `Array.from` or `Array.prototype.values`
- Still es5-ext doesn't provide the polyfills to new types as introduced by ES6, e.g. `Set` or `Map`, `WeakMap` etc.. (they're introduced with other packages). Same it doesn't provide  ES6 iterator types for types that existed with ES5 e.g. `Array`, `String`, `arguments` (that's handled by es6-iterator package)
- Functions as `Array.from` or methods as `Array.prototype.values` consume or return ES6 iterators, that's the reason`es5-ext`, needs `es6-iterator`, and as `es6-iterator` uses some ES extensions from `es5-ext` it relies on it.
