### ISSUE TITLE
Cyclic dependencies with es6-symbol, es6-iterator and d

### ISSUE THREAD

**Issue by leedm777** [medikoo/es5-ext#55]
I discovered on one of my projects that running `npm outdated` with a `--depth` of 20 or higher hung and eventually exhausted memory for the process. The cause appears to be a bunch of cyclic dependencies between the es5-ext, es5-symbol, es6-iterator and d projects.

Cyclic dependencies are generally a Bad Thing™, so I thought you might like to know. As best I can figure, here is how the projects are codependent:

![es-cycles](https://cloud.githubusercontent.com/assets/133579/21659706/a0e0db2e-d291-11e6-98c8-9e319af9f95d.png)

**Comment by medikoo** [comment]
npm supports cyclic dependencies, so it's clearly an npm bug, have you tried to open the issue there?

I'm totally aware of them in this project, and I don't see them as the issue, although there's some chance that in not that distant future it will change.

**Comment by medikoo** [comment]
Sorry I just saw that you opened the issue on npm, that's great! Let's see how they go with it :)

**Comment by leedm777** [comment]
@medikoo I hope so, too!
