### ISSUE TITLE
Warning: .then() only accepts functions but was passed [object Object] next-tick 

### ISSUE THREAD

**Issue by jasonwilliams** [medikoo/es5-ext#91]
Version: 0.10.50
I am recieving this during build. I did some investigation and `es5-ext` seems to be the only dependency using next-tick. Does this make sense?

```
(node:1025) Warning: .then() only accepts functions but was passed: [object Object]lications/desktop_front_end/node_modules/next-tick 
```

**Comment by medikoo** [comment]
@jasonwilliams this doesn't look as issue with `es5-ext`, and information you provide is insufficient to provide any hints.

If you still struggle with this, please prepare a minimal test case that involves `es5-ext` and exposes the issue with full stack trace.
