### ISSUE TITLE
es6-symbol dependency with version 3.1.2 is breaking the build.

### ISSUE THREAD

**Issue by maverickash8889** [medikoo/es5-ext#93]
`"es5-ext": {
      "version": "0.10.52",
      "resolved": "https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.52.tgz",
      "integrity": "sha512-bWCbE9fbpYQY4CU6hJbJ1vSz70EClMlDgJ7BmwI+zEJhxrwjesZRPglGJlsZhu0334U3hI+gaspwksH9IGD6ag==",
      "requires": {
        "es6-iterator": "~2.0.3",
        "es6-symbol": "~3.1.2",
        "next-tick": "~1.0.0"
      }
    },`

with the latest, CI/CD approach and the builds are failing. The es6-symbols are updated to the latest version 3.1.3. this has lead to changes in the dependency tree and earlier release is not found. build is breaking due to this.

**Comment by medikoo** [comment]
@maverickash8889 I don't think there's any error in this package configuration.

Version range for  `es6-symbol` is `~3.1.2`, which means that version should be equal or higher than `3.1.2` and lower than `3.2.0`.

Currently two versions of `es6-symbol` match that:
v3.1.2 -> https://www.npmjs.com/package/es6-symbol/v/3.1.2
v3.1.3 (latest) -> https://www.npmjs.com/package/es6-symbol/v/3.1.3
