### ISSUE TITLE
npm page has a bad github link

### ISSUE THREAD

**Issue by kyegupov** [medikoo/es5-ext#95]
https://www.npmjs.com/package/ext points to broken https://github.com/medikoo/ext :(

**Comment by medikoo** [comment]
@kyegupov Thanks for report. Thing is that `ext` is refactor of `es5-ext` which sits now in [ext](https://github.com/medikoo/es5-ext/tree/ext) branch, and until it's switched to `master` I refrain from renaming project on github.

I'll check how can I solve it with npm (maybe I can point branch somehow)

**Comment by medikoo** [comment]
Fixed repo link. Published with 1.2.1
